config/routes.rb
Qjitsu::Application.routes.draw do


  resources :dashboard
  match "dashboard" => "dashboard#index", :as => 'user_root'

  
  resources :incorrect_answers

  resources :exam_questions do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    collection do
      get  :autocomplete_tag_name
      post :ratings
      get  :sparring_mode
      get  :exam_mode
      get  :overview
      get  :get_comments
      get  :get_tags
    end
    member do
      post :add
      post :remove
      post :up
      get  :get_comments
      get  :get_tags
    end
  end


  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'
  resources :medical_cases do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    get :tags


    collection do
      get :autocomplete_tag_name
      get :autocomplete_author_name
      post :ratings
      post :result
      get  :get_comments
      get  :get_tags
    end
    member do
      post :ratings
      post :add
      post :remove
      post :approved
      post :pending
      post :draft
      post :inactive
      get  :get_comments
      get  :get_tags
    end
  end

  get 'tags/:tag', to: 'medical_cases#index', as: :tag

  resources :ratings
  resources :favorites



  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, :path_names => { :sign_up => "register" }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')


  resources :medical_organizations

  resources :medical_organizations, :except => [:destroy] do
    member do
      get :toggle_status
    end
  end

  namespace :admin do
    resources :users, :except=>[:new,:show] do
      get :toggle_status
      collection do
        get :invitations
        get :user_cases
        post :sessionclose
        get :remove_pending_invitaion
      end
    end
    resources :reports do
      collection do
        get :user_submitted_cases
        get :user_test
        get :user_aggregate
        get :questions
        get :org_assignments
      end
      member do
        get :questions
      end
    end
    resources :objectives, :except=>:show do
      member do

        get :toggle_status
      end
    end
    resources :races do
      member do
        get :toggle_status
      end
    end
    resources :medical_organizations do
      member do
        get :toggle_status
      end
    end
  end

  get "/myprofile/user_cases"
  get "/myprofile/user_history"
  get "/myprofile/exam_questions"


  post "/sent_invites" => "admin/users#send_invite", :as => 'invites'

  post "/exam_questions/up" => "exam_questions#up"
  get "/resend_invites" => "admin/users#resend_invite", :as => 'resend_invites'

  get "/myprofile" => "myprofile#edit", :as => 'profile'
  put "/profile" => "myprofile#update", :as => 'profile'

  get "about/index"
  match "/about" => "about#index"
  match "/myprofile" => "myprofile#edit"
  match '*a', :to => 'myprofile#routing'
end

app/controllers/medical_cases_controller.rb
class MedicalCasesController < ApplicationController
  include MedicalCasesHelper
  before_filter :authenticate_user!
  layout  "medical_cases"

  def index
    @search        = MedicalCase.all_models.search(params[:search])
    @filters       = OpenStruct.new(params[:search])
    @medical_cases = MedicalCase.list(current_user,params)
    @tags_count    = MedicalCase.where(:status=>"approved").tag_counts.size
    @qcount        = ExamQuestion.where(:status=>"approved").count

    @medical_case  = MedicalCase.new
    new_form
  end

  def edit
    @active_races =   Race.where(:status=>true)
    @medical_case = MedicalCase.find(params[:id])
    form_build
    render :layout => false
  end

  def show
    @medical_case = MedicalCase.find(params[:id])
  end

  def new
    @active_races =     Race.where(:status=>true)
    @medical_case = MedicalCase.new
    new_form
    render :layout => false
  end

  def create
    filters = eval(params[:search])
    @medical_case = MedicalCase.new(params[:medical_case])
    @medical_case.creator_id = current_user.id
    if @medical_case.save
      if @medical_case.check_status(params[:status])
        redirect_to medical_cases_path(:params=>filters), notice: "Your medical case is saved as a draft. In order to edit your medical case or submit your medical case to the community, please go to  <a href='#{url_for(myprofile_user_cases_path)}'>My Profile</a>"
      else
        redirect_to medical_cases_path(:params=>filters), notice:"#{current_user.role_id ==3 ? 'Medical case was successfully created. It moved for admin approval.' : 'Medical case was successfully created. It moved for approval.'}"
      end
    else
      redirect_to medical_cases_path(:params=>filters), alert: 'Medical case name already taken.'
    end
  end

  def update
    @medical_case = MedicalCase.find(params[:id])
    if @medical_case.update_attributes(params[:medical_case])
      if params[:status]!="draft"
        @medical_case.update_column(:status, "pending")
        redirect_to medical_cases_path, notice:"#{current_user.role_id ==3 ? 'Medical case was successfully created. It moved for admin approval.' : 'Medical case was successfully created. It moved for approval.'}"
      else
        redirect_to medical_cases_path, notice: "Your medical case is saved as a draft. In order to edit your medical case or submit your medical case to the community, please go to  <a href='#{url_for(myprofile_user_cases_path)}'>My Profile</a>"
      end
    end
  end


  def autocomplete_author_name
    render json: MedicalCase.auto_complete_author(params[:name])
  end

  def autocomplete_tag_name
    render json: MedicalCase.auto_complete_tag(params[:name])
  end

  def ratings
    @user_rate =    current_user.ratings.find_by_medical_case_id(params[:idBox])
    if @user_rate.nil?
      Rating.create(:medical_case_id=>params[:idBox], :user_id=>current_user.id, :rate=>params[:rate])
      user = User.find(current_user.id)
      user.update_column(:ratings_count, user.ratings.count)
    else
      @user_rate.update_column(:rate, params[:rate])
    end
    Rating.calculate_case_average
    render :json => @user_rate
  end



  def add
    @favorite =Favorite.create(:user_id=>current_user.id, :medical_case_id=> params[:id], :is_active=>true)
    render :json => @favorite
  end

  def remove
    @favorite = Favorite.find_by_user_id_and_medical_case_id(current_user.id, params[:id])
    @favorite.destroy
    render :json => @favorite
  end

  def approved
    MedicalCase.approved_cases(params)
    if params[:admin]
      redirect_to user_cases_admin_users_url, notice: 'Case is approved.'
    else
      redirect_to medical_cases_path, notice: 'Case is approved.'
    end
  end

  def draft
    @medical_case_status = MedicalCase.find(params[:id])
    @medical_case_status.draft!
    if params[:admin]
      redirect_to user_cases_admin_users_url, notice: "Case '#{@medical_case_status.title}' status changed as draft."
    else
      redirect_to medical_cases_path , notice: "Case '#{@medical_case_status.title}' status changed as draft."
    end
  end

  def pending
    @medical_case_status = MedicalCase.find(params[:id])
    @medical_case_status.pending!
    if params[:admin]
      redirect_to user_cases_admin_users_url, notice: "Case '#{@medical_case_status.title}'  is pending."
    else
      redirect_to medical_cases_path, notice: "Case '#{@medical_case_status.title}'  is pending."
    end
  end

  def inactive
    @medical_case_status = MedicalCase.find(params[:id])
    @medical_case_status.inactive!
    if params[:admin]
      redirect_to user_cases_admin_users_url,  notice: "Case '#{@medical_case_status.title}' is deactivated."
    else
      redirect_to medical_cases_path , notice: "Case '#{@medical_case_status.title}' is deactivated."
    end
  end


  def get_comments
    @mcase =MedicalCase.find(params[:id])
    render :layout=> false
  end 

  def get_tags
    @mcase = MedicalCase.find(params[:id])
    render :layout=> false
  end

end

app/helpers/medical_cases_helper.rb
module MedicalCasesHelper

	def form_build
		@medical_case.build_medical_history if @medical_case.medical_history.nil?
		@medical_case.build_review if @medical_case.review.nil?
		@medical_case.review.specific_exam_details if @medical_case.review.specific_exam_details.nil?
		@medical_case.labs.build if @medical_case.labs.nil?
		@medical_case.imagings.build if @medical_case.imagings.nil?
		@medical_case.other_studies.build if @medical_case.other_studies.nil?
		@medical_case.build_question if @medical_case.question.nil?
	end

	def new_form
		@medical_case.build_medical_history
		@medical_case.build_review
		@medical_case.review.specific_exam_details.build
		@medical_case.labs.build
		@medical_case.imagings.build
		@medical_case.other_studies.build
		@medical_case.build_question
	end

	def score_count(exam_mode)
		if exam_mode =="sparring_mode"
			current_user.score_boards.where(:exam_mode=>exam_mode, :correct=>true, :status=>"incomplete").collect(&:correct).size
		elsif exam_mode =="exam_mode"
			answers= current_user.score_boards.where(:exam_mode=>exam_mode,:status=>"incomplete").collect(&:correct)
			if answers.include?(false)
				0
			else
				answers.size
			end
		end
	end


	def level(score)
		case score
		when 0..10 then  "Grass Hopper"
		when 11..20 then "Fists of Fury"
		when 21..40 then "Enter the Dragon"
		when 40..1000 then "Grand Master"
		end
	end

	def total_time_taken
		answers= current_user.score_boards.where(:exam_mode=>"exam_mode",:status=>"incomplete").collect(&:time_taken)
		time = answers.map{|x| x.to_i}.sum

		hours = time/3600.to_i
		minutes = (time/60 - hours * 60).to_i
		seconds = (time - (minutes * 60 + hours * 3600))

		"#{'%02d' % minutes} : #{'%02d' % seconds}"
	end

end

app/views/medical_cases/_details.html.haml
%table.table
  %caption
    %h5{:style=>"text-align: left"} Patients Overviews:
  %thead
    %th Age
    %th Gender
    %th Race
    %th Chief Complaint
  %tbody
    %td= @medical_case.age
    %td= @medical_case.gender
    %td= @medical_case.race
    %td= @medical_case.chief_complaint
%hr
%h5 HPI
%p
  = @medical_case.history_of_present_illness

%hr

%table.table
  %tbody
    %tr
      %th Medication
      %th Past Medical history
    %tr
      %td= @medical_case.medical_history.medication unless @medical_case.medical_history.nil?
      %td= @medical_case.medical_history.past_medical_history
    %tr
      %th Allergies
      %th Family history
    %tr
      %td= @medical_case.medical_history.allergies
      %td= @medical_case.medical_history.family_history
%hr

%h5 ROS
%p
  some paragraps
%hr

%table.table
  %caption
    %h5{:style=>"text-align: left"} Vitals
  %thead
    %th Temperature
    %th Hear Rate
    %th Blood Pressure
    %th Respiratory Rate
    %th Sp02
  %tbody
    %td= @medical_case.review.temperature
    %td= @medical_case.review.heart_rate
    %td= @medical_case.review.blood_pressure
    %td= @medical_case.review.respiratory_rate
    %td= @medical_case.review.spo2

%h5 Physical Exam Description
%p=@medical_case.review.physical_exam_description

%h5 Abdominal Exam
- @medical_case.review.specific_exam_details.each do |pexam|
  %p= pexam.exam

%hr

%table.table
  %caption
    %h5{:style=>"text-align: left"} Labs
  %tbody
    %tr
      - @medical_case.labs.each_with_index do |x, i|
        %th= x.name
    %tr
      - @medical_case.labs.each_with_index do |x, i|
        %td= x.result

%hr

%table.table
  %caption
    %h5{:style=>"text-align: left"} Imagings
  %tbody
    %tr
      - @medical_case.imagings.each_with_index do |x, i|
        %th= x.name
    %tr
      - @medical_case.imagings.each_with_index do |x, i|
        %td= x.result

%hr

%table.table
  %caption
    %h5{:style=>"text-align: left"} Other Studies
  %tbody
    %tr
      - @medical_case.other_studies.each_with_index do |x, i|
        %th= x.name
    %tr
      - @medical_case.other_studies.each_with_index do |x, i|
        %td= x.result

app/views/medical_cases/_form.html.haml
= simple_form_for @medical_case, :validate =>true, :html => { :class => 'form-horizontal medical_case_form' } do |f|
  .modal-header
    %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times
    %h3 Make a New Case
  #next.demoarea
    .modal-body
      .row-fluid
        .span3
          %ul.nav.nav-list.nav-tabs.nav-stacked
            %li.first-tab.active
              %a(href="#general-case-info" data-toggle="tab")
                %i.icon-chevron-right.pull-right
                General Case Info
            %li.disabled
              %a(href="#medical-history" data-toggle="tab")
                %i.icon-chevron-right.pull-right
                Medical History
            %li.disabled
              %a(href="#review-of-systems" data-toggle="tab")
                %i.icon-chevron-right.pull-right
                Review of Systems
            %li.disabled
              %a(href="#labs-images-studies" data-toggle="tab")
                %i.icon-chevron-right.pull-right
                Labs, Images, Studies
            %li.last-tab.disabled
              %a(href="#add-tags" data-toggle="tab")
                %i.icon-chevron-right.pull-right
                Tags
        .span9
          .tab-content
            #general-case-info.tab-pane.active
              .form
                .row-fluid
                  .span2
                    %label.muted.required Case Title
                  .span10
                    / %input.field.span12(type="text")
                    = f.input :title , :required=>false, :label=>false,:input_html=>{class: "validate field span12"}
                .row-fluid
                  %h4#patient-overview.text-info Patient Overview
                .row-fluid.text-area
                  .span2
                    %label.muted.required Age
                    = f.input :age, :label=>false,:as =>"string", :required=>false,:input_html=>{class:"validate field span12", :min=>0 ,:max=>100}
                  .span2.offset1
                    %label.muted.required Gender
                    = f.input :gender, :label=>false,prompt: "--select--", as: :select , :collection=>["Male", "Female"],:input_html=>{class: " validate field span12"}
                  .span4.offset1
                    %label.muted.required Race
                    = f.association :race , :collection=>@active_races, prompt: "--select--", :label=>false, :input_html=>{class: "validate field span12"}
                .row-fluid.text-area
                  .span12
                    %label.muted.required Chief Complaint
                    = f.input :chief_complaint, :label=>false, :input_html=>{:rows=>"4", :class=>" validate field span12"}
                .row-fluid.text-area
                  .span12
                    %label.muted.required History of Present Illness
                    = f.input :history_of_present_illness, :label=>false, :input_html=>{:rows=>"4" , :class=>"validate field span12"}

            #medical-history.tab-pane
              = f.simple_fields_for :medical_history do |c|
                .form
                  .row-fluid
                    .span12.text-area
                      %label.muted Medications
                      = c.input :medication, :label=>false, :input_html=>{:rows=>"3", :class=>"field span12"}
                  .row-fluid
                    .span12.text-area
                      %label.muted Allergies
                      = c.input :allergies, :label=>false, :input_html=>{:rows=>"3", :class=>"field span12" }
                  .row-fluid
                    .span12.text-area
                      %label.muted Past Medical / Surgical History
                      = c.input :past_medical_history, :label=>false, :input_html=>{:rows=>"3" , :class=>"field span12"}
                  .row-fluid
                    .span12.text-area
                      %label.muted Family / Social History
                      = c.input :family_history, :label=>false, :input_html=>{:rows=>"3", :class=>"field span12" }
            #review-of-systems.tab-pane
              = f.simple_fields_for :review do |review|
                .form
                  .row-fluid
                    .span2.temp
                      %label.muted Temp
                      / %input.field.span10(type="number")
                      = review.input :temperature, :label=>false, :input_html=>{:class=>"field span10", :min=>0 }
                      %span.muted.muted-leter.pull-right F
                    .span2.offset1.hr
                      %label.muted HR
                      / %input.field.span12(type="number")
                      = review.input :heart_rate,:label=>false, :input_html=>{:class=>"field span10", :min=>0 }
                    .span2.bp
                      %label.muted BP
                      / %input.field.span12(type="number")
                      = review.input :blood_pressure,:label=>false, :input_html=>{:class=>"field span10" , :min=>0}
                    .span2.offset1.rr
                      %label.muted RR
                      / %input.field.span10(type="number")
                      = review.input :respiratory_rate, :label=>false, :input_html=>{:class=>"field span10", :min=>0 }
                      %span.muted.muted-leter /
                    .span2.sp02
                      %label.muted
                        Sp0<sub>2</sub>
                      = review.input :spo2,:label=>false, :input_html=>{:class=>"field span10", :min=>0 }
                  .row-fluid.physical-exam-desc
                    %label.muted Physical Exam Description
                    = review.input :physical_exam_description, as: :string,:label=>false, :input_html=>{:class=>"field span12" }
                  .row-fluid.exam-details-header
                    .span9
                      %p.text-info Specific Exam Details
                    .span3.text-right
                      = link_to_add_table_fields  "+ Add Specific Detail",  review, :specific_exam_details
                  %table.table.exam-detail
                    %tbody#specific_exam_details
                      = review.simple_fields_for :specific_exam_details do |e|
                        = render 'specific_exam_detail_fields', :f => e
            #labs-images-studies.tab-pane
              .form
                .row-fluid.lis-header.first
                  .span9
                    %p.text-info Labs
                  .span3.text-right
                    = link_to_add_table_fields  "+ Add Lab Result", f, :labs

                %table.lis-detail.table
                  %tbody#labs
                    = f.simple_fields_for :labs do |lab|
                      = render 'lab_fields', :f => lab
                .row-fluid.lis-header
                  .span9
                    %p.text-info Imaging
                  .span3.text-right
                    = link_to_add_table_fields  "+ Add Imaging Results", f, :imagings
                %table.lis-detail.table
                  %tbody#imagings
                    = f.simple_fields_for :imagings do |image|
                      = render 'imaging_fields', :f => image
                .row-fluid.lis-header
                  .span9
                    %p.text-info Other Studies
                  .span3.text-right
                    = link_to_add_table_fields "+ Add Study Item", f, :other_studies

                %table.lis-detail.table
                  %tbody#other_studies
                    = f.simple_fields_for :other_studies do |other|
                      = render 'other_study_fields', :f => other
            #add-tags.tab-pane
              .row-fluid
                %h4.text-info Tags
              .form
                .row-fluid
                  .span5.offset7.text-area
                    = f.input :tag_list,:input_html => {:class => 'case_tag field span12' },:label =>false, :placeholder=>"add tag"
                .row-fluid
                  .span12
                    %div.error_tag
                    .case_others_list.tags-list
                      =f.hidden_field :tag_list, :class=>'new-tag'
                %input{:type=>"hidden", :name=>"search", :id=>"filter_results",  :value=>""}

    .modal-footer
      %a.cancel(data-dismiss="modal" aria-hidden="true") Cancel
      .prev-next
        %a.btn.btn-primary.prev.disabled(href="#")
          %i.icon-chevron-left
          Previous
      //%a.btn.btn-primary.save-case(href="#" onclick="formSaveCase();") Save
      %a.btn.btn-success.disabled(href="#" onclick="submitModelForm();") Submit
      .prev-next
        %a.btn.btn-primary.next(href="#")
          Next
          %i.icon-chevron-right

app/views/medical_cases/_imaging_fields.html.haml
%tr.fields
  %td{:style=>"width: 30%;"}
    = f.input :name, :label=>false, :placeholder=> "imaging name"
  %td{:style=>"width: 30%;"}
    = f.input :result, :label=>false, :placeholder=> "imaging result"
  %td.pull-right
    = link_to_remove_fields "Delete", f

app/views/medical_cases/_lab_fields.html.haml
%tr.fields
  %td{:style=>"width: 30%;"}
    = f.input :name, :label=>false, :placeholder=> "lab name"
  %td{:style=>"width: 30%;"}
    = f.input :result, :label=>false, :placeholder=> "lab result"
  %td.pull-right
    = link_to_remove_fields "Delete", f

app/views/medical_cases/_other_study_fields.html.haml
%tr.fields
  %td{:style=>"width: 30%;"}
    = f.input :name, :label=>false, :placeholder=> "other study name"
  %td{:style=>"width: 30%;"}
    = f.input :result, :label=>false, :placeholder=> "other study result"
  %td.pull-right
    = link_to_remove_fields "Delete", f

app/views/medical_cases/_specific_exam_detail_fields.html.haml
%tr.fields
  %td{:style=>"width:90%"}
    = f.input :exam, :label=>false, :placeholder =>"enter title"
    %br/
    = f.input :detail, :label=>false, :input_html=>{:rows=>"1", :style=>"width: 560px;height: 42px;"}, :placeholder =>"enter description"
  %td
    = link_to_remove_fields  "Delete" , f

app/views/medical_cases/edit.html.haml
= render "form"

app/views/medical_cases/get_comments.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
  %h3#myModalLabel Community Comments
.modal-body
  - if @mcase.comments.empty?
    %h5.c-text
      %i No comments
  - else
    .community-case-comments
      - @mcase.comments.each do |cmt|
        .field.span6
          %a.value= link_to cmt.user, "#"
          %span.belt{:class=>"#{user_belt(cmt.user.belt)}"}
          .pull-right= cmt.created_at.strftime('%B %e, %Y ')
          %p
            = cmt.comment
          %hr
.modal-footer
  %button.pull-center.btn.btn-danger.secondary.confirm{"aria-hidden" => "true", "data-dismiss" => "modal"} Close

app/views/medical_cases/get_tags.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
  %h3#myModalLabel Tags
.modal-body
  - if @mcase.tags.empty?
    %h5.c-text
      %i No Tags
  - else
    - @mcase.tags.each do |com|
      .span.tag-head
        %span.tag
          =com.name
.modal-footer
  %button.pull-center.btn.btn-danger.secondary.confirm{"aria-hidden" => "true", "data-dismiss" => "modal"} Close

app/views/medical_cases/index.html.haml
.filtercontainer
  %h3 Filter
  .filter-fields
    = form_for "search", :action=>"medical_case", :method=>"get", :html=>{:class=>"filter_forms"} do |f|
      - if params[:search].present?
        %input{:type=>"hidden", :name=>"search[title_contains]", :id=>"searchinputvalue", :value=>"#{@filters.title_contains}"}
        %input{:type=>"hidden", :name=>"tag_name", :id=>"tag_name", :value=>params[:tag_name]}
      - else
        %input{:type=>"hidden", :name=>"search[title_contains]", :id=>"searchinputvalue", :value=>""}
        %input{:type=>"hidden", :name=>"tag_name", :id=>"tag_name", :value=>""}
      -if params[:order].present?
        %input.order_field{:type=>"hidden", :name=>"order", :value=>params[:order]}
      -else
        %input.order_field{:type=>"hidden", :name=>"order", :value=>"average"}

      .field
        %label Average Rating
        = f.select("average_rating_greater_than", [['Any', ''],['4+', 4],['3+', 3],['2+', 2],['1+', 1],], :selected => @filters.average_rating_greater_than )
      .field
        %label My Rating
        = f.select("ratings_rate_greater_than", [['Any', ''],['4+', 4],['3+', 3],['2+', 2],['1+', 1]], :selected => @filters.ratings_rate_greater_than )
      .field
        %label Author
        #auther_searchform
          %input#search_user_firstname.author_with_autocomplete.ui-autocomplete-input{:autocomplete => "off", "data-autocompleteurl" => "/medical_cases/autocomplete_author_name", :name => "search[user_firstname_contains]", :size => "30", :type => "text", :value => @filters.user_firstname_contains, :placeholder=>"enter author"}/
          %button.btn.none{:type => "submit"} GO
      .field.group
        %label.cstar-small Favorites
        #my_favorite
          =check_box_tag 'search[favorites_is_active_is_true]', 'yes', @filters.favorites_is_active_is_true=="yes"
          Show My Favs Only
          %button.btn.none{:type => "submit"} GO
      .field.group
        %label View Cases
        #answers
          %label
            =check_box_tag 'search[score_boards_correct_is_true]', '1', @filters.score_boards_correct_is_true=="1"
            %span.check-sign
              I Got Correct
          %label
            =check_box_tag 'search[score_boards_correct_is_false]', '1', @filters.score_boards_correct_is_false=="1"
            %span.x-sign
              I Got Incorrect
          %label
            =check_box_tag 'not_answer', '1', params[:not_answer]=='1'
            %span.question-sign
              I Have Not Answered
          %button.btn.none{:type => "submit"} GO
      .clear-filters
        = link_to "Clear all filters", medical_cases_path, :class=>"btn btn-primary"
    .field.group
      %label.floatleft
        .minus-tag.pull-left [-]
        Tags (#{@tags_count})      
      .clear
      .toggle_tag_form
        %form#tags_form
          %input#taginput.tags_with_autocomplete{:autocomplete =>"off", "data-autocompleteurl" => "/medical_cases/autocomplete_tag_name", :name => "tag", :size => "30", :type => "text", :placeholder=>"add tag"}/
          %button.btn.none{:type => "submit"} GO
        - if params[:tag_name].present?
          - params[:tag_name].split(',').uniq.each do |name|
            - unless !name.present?
              .labels
                =link_to content_tag(:span, "", :class=> "icon-remove remove_tag")+  name, "#",:class=>"btn btn-small btn-primary value"

.contentcontainer
  .headcontainer
    .span4
      = form_for @search, :id=>"medicals_search" do |f|
        %input{:type=>"hidden", :name=>"filter_tag", :value=>"filter_tag"}
        = f.text_field :title_contains, :id=>"searchinput",:value=>@filters.title_contains, :placeholder=>"search cases"
        .none= f.submit "Search"

    %label#sort Sort
    .form-inline
      = form_for "", :action=>"medical_case", :method=>"get", :html=>{ :class=>"order_form"} do |f|
        = f.select("order", [['Highest Average Ratings', 'average'],['Highest Personal Ratings', 'personal'],['Most Recently Authored', 'created_at'],['Author','author']], :selected => params[:order])
        .none= f.submit
    .btn-group
      - if 46 <= @qcount
        = link_to "Take", exam_mode_exam_questions_path, :class=>"btn btn-primary"
      -else
        %a.btn.btn-primary{"data-toggle" => "modal", :href => "#myModal", :role => "button"} Take
        #myModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
          .modal-body
            %h5
              =@medical_cases.size
              Medical cases should be minimum 46 cases.
              Please add medical cases.
          .modal-footer
            %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close

      %button.btn.btn-primary.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
        Make
        %span.icon-plus
      %ul.dropdown-menu.pull-right
        %li
          = link_to "Question", "#", :id=>"create-question"
        %li.divider
        %li
          / # = link_to "Case", "#", :id=>"open-new-wizard"
          / %a(href="#make-case" data-toggle="modal") Case
          %a(href="#" id="mcase" name="#{params}") Case




  .listcontainer
    %ul#medical_cases
      = render "medical_cases"
    .none= paginate @medical_cases

//place holder scripts
/[if IE]
  :javascript
    add_placeholder('searchinput', 'search cases');
    add_placeholder('search_user_firstname', 'enter author');
    add_placeholder('taginput', 'add tag');
  :css
    input#search_score_boards_correct_is_true, input#search_score_boards_correct_is_false, input#not_answer{
      margin-top: 1px !important;
    }


// New Case form
.case-form.none
  #make-case.modal.fade.container{:style => "display: none;", :tabindex => "-1"}

//comments windows
.comemnt_form.none
  #comemnts.modal.fade.container{:style => "display: none;", :tabindex => "-1"}


//tags windows
.tags_form.none
  #tags.modal.fade.container{:style => "display: none;", :tabindex => "-1"}