config/routes.rb
Qjitsu::Application.routes.draw do


  resources :dashboard
  match "dashboard" => "dashboard#index", :as => 'user_root'

  
  resources :incorrect_answers

  resources :exam_questions do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    collection do
      get  :autocomplete_tag_name
      post :ratings
      get  :sparring_mode
      get  :exam_mode
      get  :overview
      get  :get_comments
      get  :get_tags
    end
    member do
      post :add
      post :remove
      post :up
      get  :get_comments
      get  :get_tags
    end
  end


  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'
  resources :medical_cases do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    get :tags


    collection do
      get :autocomplete_tag_name
      get :autocomplete_author_name
      post :ratings
      post :result
      get  :get_comments
      get  :get_tags
    end
    member do
      post :ratings
      post :add
      post :remove
      post :approved
      post :pending
      post :draft
      post :inactive
      get  :get_comments
      get  :get_tags
    end
  end

  get 'tags/:tag', to: 'medical_cases#index', as: :tag

  resources :ratings
  resources :favorites



  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, :path_names => { :sign_up => "register" }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')


  resources :medical_organizations

  resources :medical_organizations, :except => [:destroy] do
    member do
      get :toggle_status
    end
  end

  namespace :admin do
    resources :users, :except=>[:new,:show] do
      get :toggle_status
      collection do
        get :invitations
        get :user_cases
        post :sessionclose
        get :remove_pending_invitaion
      end
    end
    resources :reports do
      collection do
        get :user_submitted_cases
        get :user_test
        get :user_aggregate
        get :questions
        get :org_assignments
      end
      member do
        get :questions
      end
    end
    resources :objectives, :except=>:show do
      member do

        get :toggle_status
      end
    end
    resources :races do
      member do
        get :toggle_status
      end
    end
    resources :medical_organizations do
      member do
        get :toggle_status
      end
    end
  end

  get "/myprofile/user_cases"
  get "/myprofile/user_history"
  get "/myprofile/exam_questions"


  post "/sent_invites" => "admin/users#send_invite", :as => 'invites'

  post "/exam_questions/up" => "exam_questions#up"
  get "/resend_invites" => "admin/users#resend_invite", :as => 'resend_invites'

  get "/myprofile" => "myprofile#edit", :as => 'profile'
  put "/profile" => "myprofile#update", :as => 'profile'

  get "about/index"
  match "/about" => "about#index"
  match "/myprofile" => "myprofile#edit"
  match '*a', :to => 'myprofile#routing'
end

app/models/race.rb
# == Schema Information
#
# Table name: races
#
#  id         :integer          not null, primary key
#  name       :string(75)       not null
#  status     :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Race < ActiveRecord::Base
  attr_accessible :name
  has_many :medical_cases


  validates :name,  :presence   => true,
                    :uniqueness => {:case_sensitive => false}
                    # :length     => {:maximum => 50 }
                    # :format   => { :with => /^[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_][a-zA-Z0-9-]*$/,:allow_blank => true }


  def change_toggle_status
    new_status = !self.status
    new_status == true ? activate : deactivate
  end

  def deactivate
    if self.medical_cases.count > 0
      msg = "Cannot deactivate '#{self.name}'. It has one or more medical cases."
      errors.add(:base, msg)
      return false
    else
      self.status = false
      self.save
    end
  end

  def activate
    self.status = true
    self.save
  end

  def to_s
    name
  end

  class << self
    def list(page_number)
      page(page_number)
    end
  end

end

app/controllers/admin/races_controller.rb
class Admin::RacesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @filters = OpenStruct.new(params[:search])
    if @filters.status_is_true =="suspend"
      @races  = Race.where(:status=>false).list(params[:page])
    elsif @filters.status_is_true =="active"
      @races  = Race.where(:status=>true).list(params[:page])
    else
      @races = Race.list(params[:page])
    end
  end

  def new
    @race = Race.new
  end

  def edit
    @race = Race.find(params[:id])
  end

  def create
    @race = Race.new(params[:race])
    if @race.save
      redirect_to admin_races_path, notice: 'Race was successfully created.'
    else
      render :action =>"new"
    end
  end

  def update
    @race = Race.find(params[:id])
    if @race.update_attributes(params[:race])
      redirect_to admin_races_path, notice: 'Race was successfully updated.'
    else
      render action: "edit"
    end
  end

  def toggle_status

    @race = Race.find(params[:id])
    name                  = @race.name
    if @race.change_toggle_status
      msg = @race.status? ? "#{name} is activated." : "#{name} is deactivated."
      redirect_to admin_races_path, notice: msg
    else
      msg = @race.errors.full_messages.to_sentence
      redirect_to admin_races_path, alert: msg
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/admin/races/_form.html.haml
=form_for [:admin, @race],:validate => true,:html => { :class => 'form-horizontal medical-org'} do |f|
  .control-group
    %label.control-label.required Name:
    = f.text_field :name, :maxlength => 50, :class => 'input-xlarge'
  .school-form
    = f.submit "Save", :class => 'btn btn-primary'
    = link_to "Cancel",  admin_races_path, :class => 'btn'

app/views/admin/races/_races.html.haml
- unless @races.empty?
  - @races.each do |race|
    %tr
      %td
        .dropdown
          %a.btn.dropdown-toggle(data-toggle="dropdown" href="#")
            Action
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "Edit", edit_admin_race_path(race),   :title => "edit"
            %li.divider
            - if race.status==true
              %li{:title => set_title_to_active(race.status)}
                = link_to content_tag(:i, '',  :class => "icon-remove-sign")+"#{race.status == true ? "Suspend" : "Activate"  }", "#",:name => "#{race.name}",  :title => "#{set_title_to_active(race.status) }", :class => "status", :id => "#{race.id}"
            - else
              %li{:title => set_title_to_active(race.status)}
                = link_to content_tag(:i, '',  :class => "icon-ok")+"#{race.status == true ? "Suspend" : "Activate"  }", "#",:name => "#{race.name}",  :title => "#{set_title_to_active(race.status) }", :class => "status", :id => "#{race.id}"
      %td.wrap= race.name
      %td= display_time(race.created_at)
      %td= race.status? ? "Active" : "Inactive"
- else
  %tr
    %td{:colspan=>4}
      .alert.alert-info{:style=>"text-align: center;"}
        No records found

app/views/admin/races/edit.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        %a(href="/admin/users")Users
      %li
        %a(href="/admin/medical_organizations" )Orgs
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li
        = link_to "Reports",admin_reports_path
      %li.active
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    %h3 Edit #{@race.name}
    %br/
    = render 'form'

app/views/admin/races/index.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        %a(href="/admin/users")Users
      %li
        %a(href="/admin/medical_organizations" )Orgs
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li
        = link_to "Reports",admin_reports_path
      %li.active
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    .tab-content
      #orgs(class="tab-pane active")
        .buttontray
          %span.pull-left View:
          .span6
            = form_for "search", :action=>"races", :method=>"get" do |f|
              = f.select("status_is_true", [["All", "all"],["Active", "active"], ["Suspend", "suspend"]], :selected => @filters.status_is_true )
          .pull-right
            = link_to "+ Add",  new_admin_race_path, :class => 'btn btn-primary medical_new pull-right'
        %table.table.table-striped
          %thead
            %tr
              %th{:width=>"130px"}
              %th.span4 Name
              %th Creation Date
              %th Status
          %tbody#races
            = render "races"
            .none= paginate @races
#modal-from-dom.modal.hide.fade
  .modal-header
    %button.close{"data-dismiss" => "modal", :type => "button"} &times;
    %h3 Race
  .modal-body
    %p Do you want to proceed?
  .modal-footer
    %a#yes_id.btn.btn-primary.danger.confirm Yes
    %a#no_id.btn.btn-danger.secondary.confirm{"data-dismiss" => "modal", :type => "button"} No

app/views/admin/races/index.js.erb
$("#races").append("<%= j render('races')%>");
<% unless @races.last_page? %>
  $(".pagination").replaceWith("<%= j paginate @races %>");
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/races/new.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        %a(href="/admin/users")Users
      %li
        %a(href="/admin/medical_organizations" )Orgs
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li
        = link_to "Reports",admin_reports_path
      %li.active
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    %h3 Add New Race
    %br
  = render 'form'