config/routes.rb
Qjitsu::Application.routes.draw do


  resources :dashboard
  match "dashboard" => "dashboard#index", :as => 'user_root'

  
  resources :incorrect_answers

  resources :exam_questions do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    collection do
      get  :autocomplete_tag_name
      post :ratings
      get  :sparring_mode
      get  :exam_mode
      get  :overview
      get  :get_comments
      get  :get_tags
    end
    member do
      post :add
      post :remove
      post :up
      get  :get_comments
      get  :get_tags
    end
  end


  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'
  resources :medical_cases do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    get :tags


    collection do
      get :autocomplete_tag_name
      get :autocomplete_author_name
      post :ratings
      post :result
      get  :get_comments
      get  :get_tags
    end
    member do
      post :ratings
      post :add
      post :remove
      post :approved
      post :pending
      post :draft
      post :inactive
      get  :get_comments
      get  :get_tags
    end
  end

  get 'tags/:tag', to: 'medical_cases#index', as: :tag

  resources :ratings
  resources :favorites



  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, :path_names => { :sign_up => "register" }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')


  resources :medical_organizations

  resources :medical_organizations, :except => [:destroy] do
    member do
      get :toggle_status
    end
  end

  namespace :admin do
    resources :users, :except=>[:new,:show] do
      get :toggle_status
      collection do
        get :invitations
        get :user_cases
        post :sessionclose
        get :remove_pending_invitaion
      end
    end
    resources :reports do
      collection do
        get :user_submitted_cases
        get :user_test
        get :user_aggregate
        get :questions
        get :org_assignments
      end
      member do
        get :questions
      end
    end
    resources :objectives, :except=>:show do
      member do

        get :toggle_status
      end
    end
    resources :races do
      member do
        get :toggle_status
      end
    end
    resources :medical_organizations do
      member do
        get :toggle_status
      end
    end
  end

  get "/myprofile/user_cases"
  get "/myprofile/user_history"
  get "/myprofile/exam_questions"


  post "/sent_invites" => "admin/users#send_invite", :as => 'invites'

  post "/exam_questions/up" => "exam_questions#up"
  get "/resend_invites" => "admin/users#resend_invite", :as => 'resend_invites'

  get "/myprofile" => "myprofile#edit", :as => 'profile'
  put "/profile" => "myprofile#update", :as => 'profile'

  get "about/index"
  match "/about" => "about#index"
  match "/myprofile" => "myprofile#edit"
  match '*a', :to => 'myprofile#routing'
end

app/models/report.rb
#This is required to make only authorized users  access reports controller actions
class Report
	def self.user_report(filters,sort,page)

		user_q = ""
		user_q << " (lastname ilike '%"+filters.name+"%' or firstname ilike '%"+filters.name+"%' or email ilike '%"+filters.name+"%') and" unless filters.name.nil? or filters.name.empty?
		user_q << " medical_organization_id = "+filters.org_id+" and" unless filters.org_id.nil? or filters.org_id.empty?
		user_q << " (questions_count > 0 and comments_count > 0 and ratings_count > 0)" if !filters.hide_users.nil? and filters.hide_users="yes"
		user_q = user_q.chomp("and")


		exam_questions_count_q =  "(select count(exam_questions.id) from exam_questions where exam_questions.creator_id = users.id and exam_questions.status='approved'"
		exam_questions_count_q << " and exam_questions.objective_id = "+filters.exam_questions_objective_id_in if !filters.exam_questions_objective_id_in.nil? and !filters.exam_questions_objective_id_in.empty?
		exam_questions_count_q << " and exam_questions.created_at >= '"+filters.created_at_gte.to_s+"'" if !filters.created_at_gte.nil?
		exam_questions_count_q << " and exam_questions.created_at <= '"+filters.created_at_lte.to_s+"'" if !filters.created_at_lte.nil?
		exam_questions_count_q << ")"
		
		exam_questions_list_q = ""
		exam_questions_list_q << "select id from exam_questions where objective_id = "+filters.exam_questions_objective_id_in if !filters.exam_questions_objective_id_in.nil? and !filters.exam_questions_objective_id_in.empty?

		comments_count_q =  "(select count(comments.id) from comments where comments.user_id = users.id and commentable_type =  'ExamQuestion'"
		comments_count_q << " and comments.created_at >= '"+filters.created_at_gte.to_s+"'" if !filters.created_at_gte.nil?
		comments_count_q << " and comments.created_at <= '"+filters.created_at_lte.to_s+"'" if !filters.created_at_lte.nil?
		comments_count_q << " and comments.commentable_id in ("+exam_questions_list_q+")" if !filters.exam_questions_objective_id_in.nil? and !filters.exam_questions_objective_id_in.empty?
		comments_count_q << ")"

		ratings_count_q =  "(select count(ratings.id) from ratings where ratings.user_id = users.id"
		ratings_count_q << " and ratings.created_at >= '"+filters.created_at_gte.to_s+"'" if !filters.created_at_gte.nil?
		ratings_count_q << " and ratings.created_at <= '"+filters.created_at_lte.to_s+"'" if !filters.created_at_lte.nil?
		ratings_count_q << " and ratings.exam_question_id in ("+exam_questions_list_q+")" if !filters.exam_questions_objective_id_in.nil? and !filters.exam_questions_objective_id_in.empty?
		ratings_count_q << " and ratings.exam_question_id is not null" if filters.exam_questions_objective_id_in.nil? or filters.exam_questions_objective_id_in.empty?
		ratings_count_q << ")"
		users = User.select("users.id, users.lastname, users.firstname, users.email," \
							+" "+exam_questions_count_q+" as questions_count,"\
							+" "+comments_count_q+" as comments_count,"\
							+" "+ratings_count_q+" as ratings_count "\
							)
					.where(user_q)
					.joins("left outer join exam_questions on (exam_questions.creator_id = users.id)")
					.joins("left outer join comments on (comments.user_id = users.id)")
					.joins("left outer join ratings on (ratings.user_id = users.id)")
					.group("users.id")
					.order(sort.col+" "+sort.dir)
		users = users.page(page.page).per(page.per) if page.paginated
		users
	end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_filter :authenticate_user!
  before_filter :convert_datetimepicker_dates, :only => [:user_submitted_cases]

  load_and_authorize_resource
  handles_sortable_columns
  def index
    @users = User.list(params[:page])

    # @sparing_mode = current_user.score_boards.where(:exam_mode=>"sparing_mode").group_by(&:exam_number).sort.reverse
    # @test_mode =current_user.score_boards.where(:exam_mode=>"exam_mode").group_by(&:exam_number).sort.reverse

    respond_to do |format|
      format.html
      format.js
    end
  end

  def user_submitted_cases
    require 'csv'
    @filters = OpenStruct.new(params[:search_filter])
    @sort =   OpenStruct.new(:col => sort_column, :dir=> sort_direction)
    @page =   OpenStruct.new(:page => params[:page], :per=>params[:per], :paginated=>params[:format].nil?) #CSV or XLS are not paginated
    @users   = Report.user_report(@filters,@sort,@page)

    respond_to do |format|
      format.html
      format.js
      format.csv
      format.xls
    end
  end

  def user_test
    @users = User.includes(:score_boards).list(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def user_aggregate
    @users = User.list(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def questions
    user = User.find(params[:user_id])
    params[:search] ={}
    params[:search][:status_contains] = "approved"
    params[:search][:created_at_gte]  = params[:from] if params[:from].present? and params[:from] != "undefined"
    params[:search][:created_at_lte]  = params[:to]   if params[:to].present? and params[:to] != "undefined"
    params[:search][:objective_id_in] = params[:obj]  if params[:obj].present? and params[:obj] != "undefined"    
    s=  user.exam_questions.search(params[:search])
    questions =  s.all.collect(&:question_prompt)
    render :json=> questions
  end

  #convert datetimepicker string parameters to Time objects (in views these are converted back into the appropriate string using display_time helper method
  def convert_datetimepicker_dates
    if params[:search_filter].present?
      params[:search_filter][:created_at_gte] = convert_datetime_pickerdate(params[:search_filter][:created_at_gte])
      params[:search_filter][:created_at_lte] = convert_datetime_pickerdate(params[:search_filter][:created_at_lte])
    end
  end

  def convert_datetime_pickerdate(chosen_date)
    Time.strptime(chosen_date,"%m/%d/%Y %H:%M %p %Z") unless chosen_date.nil? or chosen_date.empty?
  rescue ArgumentError # regular timestamp is MM/DD/YY HH:MM PP Z, but download as CSV sends the date as YY-MM-DD HH:MM:SS Z 
    Time.strptime(chosen_date,"%Y-%m-%d %H:%M:%S %Z") unless chosen_date.nil? or chosen_date.empty?
  end

  def org_assignments
    if params[:org].present?
      org         = MedicalOrganization.find(params[:org])    
      assignments = Objective.where_status_is_open_or_closed().where(:medical_organization_id=>org).order('name asc').collect {|p| [ p.name, p.id ] }
    else
      assignments = Objective.where_status_is_open_or_closed().order('name asc').collect {|p| [ p.name, p.id ] } 
    end
    render :json=> assignments
  end


  private

  #todo lock down options on sort columns and parameters
  def sort_column
    column = params[:qcol] || "lastname"
  end
  def sort_direction
    direction = params[:qdir] || "asc"
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
	def total_time_taken_report(user, mode)
		answers= user.score_boards.where(:exam_mode=>mode).collect(&:time_taken)
		time = answers.map{|x| x.to_i}.sum
				
		hours = time/3600.to_i
		minutes = (time/60 - hours * 60).to_i
		seconds = (time - (minutes * 60 + hours * 3600))
		return seconds
	end

	def qsortable(column, title=nil)
		title  ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction =  column == sort_column && sort_direction =="asc" ? "desc" : "asc"
		link_to title, params.merge(:qcol => column, :qdir => direction, :page => nil), {:class=>css_class}
	end
end

app/views/admin/reports/_user_aggregate.html.haml
- @users.each do |user|
  %tr
    %td.wrap= user.full_name
    %td= user.email
    %td
      = user.belt

app/views/admin/reports/_user_submitted_cases.html.haml
=hidden_field_tag :qdir, sort_direction
=hidden_field_tag :qcol, sort_column

.pull-left
  =paginate @users, :theme => 'qpaginate'

.btn-group.pull-right
  %button.btn.btn-default.dropdown-toggle{:type => "button", :'data-toggle'=>"dropdown"}
    Download
    %span.caret
  %ul.dropdown-menu{:role=>"menu"}
    %li= link_to "CSV", {format: "csv", params: params.merge({:page=>nil})}
    %li= link_to "Excel", {format: "xls", params: params.merge({:page=>nil})}

%table.table.table-striped.clear
  %thead
    %tr
      %th{:style=>"width:140px;"}= qsortable "lastname", "Last Name"
      %th{:style=>"width:140px;"}= qsortable "firstname", "First Name"
      %th{:style=>"width:360px;"}= qsortable "email"
      %th.c-text=  qsortable "questions_count", "Total Questions"
      %th.c-text=  qsortable "comments_count",  "Total Comments"
      %th.c-text=  qsortable "ratings_count",   "Total Ratings"
  %tbody
    - if !@users.empty? and @users.count.size > 0
      - @u = []
      - @users.each do |user|
        %tr
          %td.wrap= user.lastname
          %td.wrap= user.firstname
          %td=user.email
          /%td.c-text= link_to user.questions_count, "#", :class=>"list-question", :obj=>@filters.exam_questions_objective_id_in,  :from=>@filters.created_at_gte, :to=>@filters.created_at_lte, :id=> user.id, "data-toggle"=>"modal"
          %td.c-text= user.questions_count
          %td.c-text= user.comments_count
          %td.c-text= user.ratings_count
    - else
      %tr
        %td{:colspan=>7}
          .alert.alert-info
            No records found


/#myModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
/  .modal-header
/    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
/    %h3#myModalLabel Questions
/  .modal-body
/    #question-prompts
/  .modal-footer
/    %button.btn.btn-danger{"aria-hidden" => "true", "data-dismiss" => "modal"} Close

app/views/admin/reports/_user_test.html.haml
- @users.each do |user|
  %tr
    %td.wrap= user.full_name
    %td.c-text= number_of_exam(user, 'sparring_mode')
    %td.c-text= total_questions(user, 'sparring_mode')
    %td.c-text= user_report_high_score(user, 'sparring_mode')
    %td.c-text= total_time_taken_report(user, 'sparring_mode')
    %td.c-text= number_of_exam(user, 'exam_mode')
    %td.c-text= total_questions(user, 'exam_mode')
    %td.c-text= user_report_high_score(user, 'exam_mode')
    %td.c-text= total_time_taken_report(user, 'exam_mode')

app/views/admin/reports/_users.html.haml
- @users.each do |user|  
  %tr
    %td.wrap= user.full_name
    %td= user.email
    %td.c-text= user.sign_in_count
    %td.c-text
      - unless user.average_session_time.nil?
        =distance_of_time_in_words(user.average_session_time).capitalize

app/views/admin/reports/index.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        =link_to "Users" , admin_users_path
      %li
        =link_to "Orgs" , admin_medical_organizations_path
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li.active
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    .tab-content
      #reports(class="tab-pane active")
        .tabbable
          %ul.nav.nav-tabs
            %li.active
              =link_to "Activity" , admin_reports_path
            %li
              =link_to "Contributions", user_submitted_cases_admin_reports_path
            %li
              =link_to "Exam Scores", user_test_admin_reports_path
            %li
              =link_to "Belt Levels", user_aggregate_admin_reports_path
          .tab-content
            #Invite(class="tab-pane active")
              %h5 Activity
              %table.table.table-striped
                %thead
                  %tr
                    %th.span4 Name
                    %th.span4 Email
                    %th.c-text Number of Logins
                    %th.c-text Average Browser Session Time
                %tbody#users
                  = render "users"
              .none= paginate @users

app/views/admin/reports/index.js.erb
$("#users").append("<%= j render('users')%>");
<% unless @users.last_page? %>
  $(".pagination").replaceWith("<%= j paginate @users %>");
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/reports/user_aggregate.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        =link_to "Users" , admin_users_path
      %li
        =link_to "Orgs" , admin_medical_organizations_path
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li.active
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    .tab-content
      #reports(class="tab-pane active")
        .tabbable
          %ul.nav.nav-tabs
            %li
              =link_to "Activity" , admin_reports_path
            %li
              =link_to "Contributions", user_submitted_cases_admin_reports_path
            %li
              =link_to "Exam Scores", user_test_admin_reports_path
            %li.active
              =link_to "Belt Levels", user_aggregate_admin_reports_path
          .tab-content
            #Invite(class="tab-pane active")
              %h5 Belt Levels
              %table.table.table-striped
                %thead
                  %tr
                    %th.span4  Name
                    %th.span4  Email
                    %th.span2  Belt                    
                %tbody#user_aggregate
                  = render "user_aggregate"
              .none= paginate @users

app/views/admin/reports/user_aggregate.js.erb
$("#user_aggregate").append("<%= j render('user_aggregate')%>");
<% unless @users.last_page? %>
  $(".pagination").replaceWith("<%= j paginate @users %>");
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/reports/user_submitted_cases.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        =link_to "Users" , admin_users_path
      %li
        =link_to "Orgs" , admin_medical_organizations_path
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li.active
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    .tab-content
      #reports(class="tab-pane active")
        .tabbable
          %ul.nav.nav-tabs
            %li
              =link_to "Activity" , admin_reports_path
            %li.active
              =link_to "Contributions", user_submitted_cases_admin_reports_path
            %li
              =link_to "Exam Scores", user_test_admin_reports_path
            %li
              =link_to "Belt Levels", user_aggregate_admin_reports_path
          .tab-content
            #Invite(class="tab-pane active")
              .buttontray
                = form_for "search_filter", :action=>"admin/reports/user_submitted_cases", :method=>"get", :html=>{:class=>"qsearchable"} do |f|
                  .well
                    %table.report-filter
                      %tbody
                        %tr
                          %th Name / Email
                          %th Organization
                          %th Assignment
                          %th Date Range
                        %tr
                          %td= f.text_field :name, :value=>"#{@filters.name unless @filters.name.nil?}"
                          %td= f.select(:org_id, MedicalOrganization.where(:status=>true).map{|x|[x.name, x.id]}, :include_blank=>true, :selected=>@filters.org_id )
                          %td= f.select(:exam_questions_objective_id_in, Objective.where_status_is_open_or_closed().collect {|p| [ p.name, p.id ] }, :include_blank=>true, :selected=>@filters.exam_questions_objective_id_in)
                          %td
                            - dateFormat = "MM/dd/yyyy HH:mm PP #{Time.now.in_time_zone.strftime("%Z")}"
                            .input-append.datetimepicker{"data-end-date"=>display_time(Time.now), :class=>"date"}
                              = f.text_field :created_at_gte, :'data-format'=>dateFormat, :value=>"#{display_time(@filters.created_at_gte,:datetime_picker)}", :placeholder=>'From'
                              %span.add-on
                                %i.icon-calendar
                          %td
                            .input-append.datetimepicker{"data-end-date"=>display_time(Time.now), :class=>"date"}
                              = f.text_field :created_at_lte, :'data-format'=>dateFormat, :value=>"#{display_time(@filters.created_at_lte,:datetime_picker)}", :placeholder=>'To'
                              %span.add-on
                                %i.icon-calendar
                        %tr
                          %td
                          %td
                          %td
                            %label.checkbox
                              =check_box_tag 'search_filter[hide_users]', 'yes', @filters.hide_users=="yes"
                              Hide users with no contributions
                        %tr
                          %td
                            = f.submit "Search", :class => 'btn btn-primary'
                            = link_to "Clear",user_submitted_cases_admin_reports_path,  :class => 'btn'
                  #qpaginated
                    = render "user_submitted_cases"

app/views/admin/reports/user_submitted_cases.js.erb
$("#qpaginated").html('<%= j render('user_submitted_cases')%>');

app/views/admin/reports/user_submitted_cases.xls.haml
%table
    %thead
        %tr
            %th Last Name
            %th First Name
            %th Email
            %th Total Questions
            %th Total Comments
            %th Total Ratings
    %tbody
    -@users.each do |user|
        %tr
            %td= user.lastname
            %td= user.firstname
            %td= user.email
            %td= user.questions_count
            %td= user.comments_count
            %td= user.ratings_count

app/views/admin/reports/user_test.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        =link_to "Users" , admin_users_path
      %li
        =link_to "Orgs" , admin_medical_organizations_path
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li.active
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    .tab-content
      #reports(class="tab-pane active")
        .tabbable
          %ul.nav.nav-tabs
            %li
              =link_to "Activity" , admin_reports_path
            %li
              =link_to "Contributions", user_submitted_cases_admin_reports_path
            %li.active
              =link_to "Exam Scores", user_test_admin_reports_path
            %li
              =link_to "Belt Levels", user_aggregate_admin_reports_path
          .tab-content
            #Invite(class="tab-pane active")
              %h5 Exam Scores
              %table.table.table-striped
                %thead
                  %tr
                    %th  Name
                    %th.c-text  No.of Test - Sparring Mode
                    %th.c-text  Total Questions Answered - Sparring Mode
                    %th.c-text High Score - Sparring Mode
                    %th.c-text Total Time Taken - Sparring Mode (sec)
                    %th.c-text No.of Test - Exam Mode
                    %th.c-text Total Questions Answered - Exam Mode
                    %th.c-text High Score - Exam Mode
                    %th.c-text Total Time Taken - Exam Mode (sec)
                %tbody#user_test
                  = render "user_test"
              .none= paginate @users

app/views/admin/reports/user_test.js.erb
$("#user_test").append("<%= j render('user_test')%>");
<% unless @users.last_page? %>
  $(".pagination").replaceWith("<%= j paginate @users %>");
<% else %>
  $('.pagination').remove();
<% end %>