config/routes.rb
Qjitsu::Application.routes.draw do


  resources :dashboard
  match "dashboard" => "dashboard#index", :as => 'user_root'

  
  resources :incorrect_answers

  resources :exam_questions do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    collection do
      get  :autocomplete_tag_name
      post :ratings
      get  :sparring_mode
      get  :exam_mode
      get  :overview
      get  :get_comments
      get  :get_tags
    end
    member do
      post :add
      post :remove
      post :up
      get  :get_comments
      get  :get_tags
    end
  end


  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'
  resources :medical_cases do
    resources :comments
    resources :score_boards, :only => [:create, :update]
    get :tags


    collection do
      get :autocomplete_tag_name
      get :autocomplete_author_name
      post :ratings
      post :result
      get  :get_comments
      get  :get_tags
    end
    member do
      post :ratings
      post :add
      post :remove
      post :approved
      post :pending
      post :draft
      post :inactive
      get  :get_comments
      get  :get_tags
    end
  end

  get 'tags/:tag', to: 'medical_cases#index', as: :tag

  resources :ratings
  resources :favorites



  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, :path_names => { :sign_up => "register" }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')


  resources :medical_organizations

  resources :medical_organizations, :except => [:destroy] do
    member do
      get :toggle_status
    end
  end

  namespace :admin do
    resources :users, :except=>[:new,:show] do
      get :toggle_status
      collection do
        get :invitations
        get :user_cases
        post :sessionclose
        get :remove_pending_invitaion
      end
    end
    resources :reports do
      collection do
        get :user_submitted_cases
        get :user_test
        get :user_aggregate
        get :questions
        get :org_assignments
      end
      member do
        get :questions
      end
    end
    resources :objectives, :except=>:show do
      member do

        get :toggle_status
      end
    end
    resources :races do
      member do
        get :toggle_status
      end
    end
    resources :medical_organizations do
      member do
        get :toggle_status
      end
    end
  end

  get "/myprofile/user_cases"
  get "/myprofile/user_history"
  get "/myprofile/exam_questions"


  post "/sent_invites" => "admin/users#send_invite", :as => 'invites'

  post "/exam_questions/up" => "exam_questions#up"
  get "/resend_invites" => "admin/users#resend_invite", :as => 'resend_invites'

  get "/myprofile" => "myprofile#edit", :as => 'profile'
  put "/profile" => "myprofile#update", :as => 'profile'

  get "about/index"
  match "/about" => "about#index"
  match "/myprofile" => "myprofile#edit"
  match '*a', :to => 'myprofile#routing'
end

app/models/medical_organization.rb
# == Schema Information
#
# Table name: medical_organizations
#
#  id          :integer          not null, primary key
#  name        :string(75)       not null
#  status      :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  users_count :integer          default(0)
#

class MedicalOrganization < ActiveRecord::Base
  include RestrictDeletion
  extend RestrictDeletion::ClassMethods

  #Mass assignment
  attr_accessible :name

  #Strip white spaces
  normalize_attribute :name, :with => :strip

  #Associations
  has_many :users
  has_many :invites
  has_many :objectives
  #scopes
  default_scope order(:name)
  scope :where_active, -> {where("status"=>true)}
  

  validates :name, :presence   => true,
                   :uniqueness => {:case_sensitive => false}
                   # :length     => {:maximum => 50 }

  def creation_date
    created_at.try(:strftime, "%b %d, %Y")
  end

  def active_status
    status? ? "Active" : "Inactive"
  end

  def total_members
    users.count
  end

  def deactivate
    if self.users.count > 0
      msg = "Cannot deactivate '#{self.name}'. It has one or more members."
      errors.add(:base, msg)
      return false
    else
      self.status = false
      self.save
    end
  end

  def activate
    self.status = true
    self.save
  end

  def change_toggle_status
    new_status = !self.status
    new_status == true ? activate : deactivate
  end

  class << self
    def list(page_number)
      page(page_number)
    end
  end
end

app/controllers/admin/medical_organizations_controller.rb
class Admin::MedicalOrganizationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @filters = OpenStruct.new(params[:search])

    if @filters.status_is_true =="suspend"
      @medical_organizations  = MedicalOrganization.where(:status=>false).list(params[:page])
    elsif @filters.status_is_true =="active"
      @medical_organizations  = MedicalOrganization.where(:status=>true).list(params[:page])
    else
      @medical_organizations = MedicalOrganization.list(params[:page])
    end

  end


  def new
    @medical_organization = MedicalOrganization.new
  end

  def edit
    @medical_organization = MedicalOrganization.find(params[:id])
  end

  def create
    @medical_organization        = MedicalOrganization.new(params[:medical_organization])
    @medical_organization.status = true

    if @medical_organization.save
      redirect_to admin_medical_organizations_path , notice: 'Medical organization created successfully.'
    else
      render action: "new"
    end
  end

  def update
    @medical_organization = MedicalOrganization.find(params[:id])
    if @medical_organization.update_attributes(params[:medical_organization])
      redirect_to admin_medical_organizations_path, notice: 'Medical organization updated successfully.'
    else
      render action: "edit"
    end
  end

  def toggle_status
    @medical_organization = MedicalOrganization.find(params[:id])
    name                  = @medical_organization.name
    if @medical_organization.change_toggle_status
      msg = @medical_organization.status? ? "#{name} is activated." : "#{name} is deactivated."
      redirect_to admin_medical_organizations_path, notice: msg
    else
      msg = @medical_organization.errors.full_messages.to_sentence
      redirect_to admin_medical_organizations_path, alert: msg
    end
  end
end

app/helpers/medical_organizations_helper.rb
module MedicalOrganizationsHelper
end

app/views/admin/medical_organizations/_form.html.haml
=form_for [:admin, @medical_organization],:validate => true,:html => { :class => 'form-horizontal medical-org'} do |f|
  .control-group
    %label.control-label.required Name:
    = f.text_field :name, :maxlength => 50, :class => 'input-xlarge'
  .school-form
    = f.submit "Save", :class => 'btn btn-primary'
    = link_to "Cancel",  admin_medical_organizations_path, :class => 'btn'

app/views/admin/medical_organizations/_medical_organizations.html.haml
- unless @medical_organizations.empty?
  - @medical_organizations.each_with_index do |medical_organization, index|
    %tr
      %td
        .dropdown
          %a.btn.dropdown-toggle(data-toggle="dropdown" href="#")
            Action
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "Edit", edit_admin_medical_organization_path(medical_organization),   :title => "edit"
            %li.divider
            - if medical_organization.status==true
              %li{:title => set_title_to_active(medical_organization.status)}
                = link_to content_tag(:i, '',  :class => "icon-remove-sign")+"#{medical_organization.status == true ? "Suspend" : "Activate"  }", "#",:name => "#{medical_organization.name}",  :title => "#{set_title_to_active(medical_organization.status) }", :class => "status", :id => "#{medical_organization.id}"
            - else
              %li{:title => set_title_to_active(medical_organization.status)}
                = link_to content_tag(:i, '',  :class => "icon-ok")+"#{medical_organization.status == true ? "Suspend" : "Activate"  }", "#",:name => "#{medical_organization.name}",  :title => "#{set_title_to_active(medical_organization.status) }", :class => "status", :id => "#{medical_organization.id}"

      %td.wrap= medical_organization.name
      %td= medical_organization.creation_date
      %td#members.c-text= medical_organization.total_members
      %td= medical_organization.active_status

- else
  %tr
    %td{:colspan=>4}
      .alert.alert-info{:style=>"text-align: center;"}
        No records found

app/views/admin/medical_organizations/edit.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        %a(href="/admin/users")Users
      %li.active
        %a(href="/admin/medical_organizations" )Orgs
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    %h3 Edit #{@medical_organization.name}
    %br/

    = render 'form'

app/views/admin/medical_organizations/index.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        %a(href="/admin/users")Users
      %li.active
        %a(href="/admin/medical_organizations" )Orgs
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    .tab-content
      #orgs(class="tab-pane active")
        .buttontray
          %span.pull-left View:
          .span3
            = form_for "search", :action=>"admin/medical_organizations", :method=>"get" do |f|
              = f.select("status_is_true", [["All", "all"],["Active", "active"], ["Suspend", "suspend"]], :selected => @filters.status_is_true )
          .pull-right
            = link_to "+ Add",  new_admin_medical_organization_path, :class => 'btn btn-primary medical_new pull-right'
        %table.table.table-striped
          %thead
            %tr
              %th{:width=>"130px"}
              %th.span4 Name
              %th Creation Date
              %th.c-text No. of members
              %th Status
          %tbody#medical_organizations
            = render "medical_organizations"
        .none= paginate @medical_organizations

#modal-from-dom.modal.hide.fade
  .modal-header
    %button.close{"data-dismiss" => "modal", :type => "button"} &times;
    %h3 Medical organization
  .modal-body
    %p Do you want to proceed?
  .modal-footer
    %a#yes_id.btn.btn-primary.danger.confirm Yes
    %a#no_id.btn.btn-danger.secondary.confirm{"data-dismiss" => "modal", :type => "button"} No

/[if IE]
  :javascript
    add_placeholder('invite_email', 'email');

app/views/admin/medical_organizations/index.js.erb
$("#medical_organizations").append("<%= j render('medical_organizations')%>");
<% unless @medical_organizations.last_page? %>
  $(".pagination").replaceWith("<%= j paginate @medical_organizations %>");
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/medical_organizations/new.html.haml
.sectionpad
  .tabbable
    %ul.nav.nav-tabs
      %li
        %a(href="/admin/users")Users
      %li.active
        %a(href="/admin/medical_organizations" )Orgs
      %li
        =link_to "Cases", user_cases_admin_users_path
      %li
        =link_to "Invitations", invitations_admin_users_path
      %li
        = link_to "Reports",admin_reports_path
      %li
        = link_to "Races",admin_races_path
      %li
        = link_to "Assignments",admin_objectives_path
    %h3 Add New Medical Organization
    %br
    = render 'form'